# Generated by Django 3.1.13 on 2022-03-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn13', models.TextField()),
                ('isbn10', models.TextField()),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('authors', models.TextField()),
                ('categories', models.TextField()),
                ('thumbnail', models.TextField()),
                ('description', models.TextField()),
                ('published_year', models.IntegerField()),
                ('average_rating', models.IntegerField()),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
            ],
        ),
    ]
