# Generated by Django 3.1.13 on 2022-03-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn10', models.TextField()),
                ('title', models.TextField()),
                ('subtitle', models.TextField()),
                ('authors', models.TextField()),
                ('categories', models.TextField()),
                ('thumbnail', models.TextField()),
                ('description', models.TextField()),
                ('published_year', models.IntegerField()),
                ('average_rating', models.IntegerField()),
                ('num_pages', models.IntegerField()),
                ('ratings_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReadingList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=None, max_length=300)),
                ('favourites', models.CharField(blank=True, default=None, max_length=3000)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
