# Generated by Django 3.1.13 on 2022-04-04 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readinglist',
            old_name='favourites',
            new_name='readlist',
        ),
    ]
